engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - sickbeard/**
exclude_paths:
- lib/*