from hachoir.parser.audio.aiff import AiffFile
from hachoir.parser.audio.au import AuFile
from hachoir.parser.audio.itunesdb import ITunesDBFile
from hachoir.parser.audio.ipod_playcounts import PlayCountFile
from hachoir.parser.audio.midi import MidiFile
from hachoir.parser.audio.mpeg_audio import MpegAudioFile
from hachoir.parser.audio.real_audio import RealAudioFile
from hachoir.parser.audio.xm import XMModule
from hachoir.parser.audio.s3m import S3MModule
from hachoir.parser.audio.s3m import PTMModule
from hachoir.parser.audio.mod import AmigaModule
from hachoir.parser.audio.flac import FlacParser
