from tornado_py3 import ioloop as ioloop, process as process
from tornado_py3.log import gen_log as gen_log
from tornado_py3.util import exec_in as exec_in
from typing import Callable

def start(check_time: int=...) -> None: ...
def wait() -> None: ...
def watch(filename: str) -> None: ...
def add_reload_hook(fn: Callable[[], None]) -> None: ...
def main() -> None: ...
