import logging.handlers
from tornado_py3.util import basestring_type as basestring_type, unicode_type as unicode_type
from typing import Any, Dict

access_log: Any
app_log: Any
gen_log: Any

class LogFormatter(logging.Formatter):
    DEFAULT_FORMAT: str = ...
    DEFAULT_DATE_FORMAT: str = ...
    DEFAULT_COLORS: Any = ...
    def __init__(self, fmt: str=..., datefmt: str=..., style: str=..., color: bool=..., colors: Dict[int, int]=...) -> None: ...
    def format(self, record: Any) -> str: ...

def enable_pretty_logging(options: Any=..., logger: logging.Logger=...) -> None: ...
def define_logging_options(options: Any=...) -> None: ...
