from typing import Any, Optional

class _LooseFeedParser:
    contentparams: Any = ...
    baseuri: Any = ...
    lang: Any = ...
    encoding: Any = ...
    entities: Any = ...
    def __init__(self, baseuri: Optional[Any] = ..., baselang: Optional[Any] = ..., encoding: Optional[Any] = ..., entities: Optional[Any] = ...) -> None: ...
    @staticmethod
    def _normalize_attributes(kv: Any): ...
    def decode_entities(self, element: Any, data: Any): ...
    @staticmethod
    def strattrs(attrs: Any): ...
