from ..exceptions import UndeclaredNamespace as UndeclaredNamespace
from typing import Any

class _StrictFeedParser:
    bozo: int = ...
    exc: Any = ...
    decls: Any = ...
    baseuri: Any = ...
    lang: Any = ...
    encoding: Any = ...
    def __init__(self, baseuri: Any, baselang: Any, encoding: Any) -> None: ...
    @staticmethod
    def _normalize_attributes(kv: Any): ...
    def startPrefixMapping(self, prefix: Any, uri: Any) -> None: ...
    def startElementNS(self, name: Any, qname: Any, attrs: Any) -> None: ...
    def characters(self, text: Any) -> None: ...
    def endElementNS(self, name: Any, qname: Any) -> None: ...
    def error(self, exc: Any) -> None: ...
    warning: Any = ...
    def fatalError(self, exc: Any) -> None: ...
