from hachoir_py2.parser.audio.aiff import AiffFile
from hachoir_py2.parser.audio.au import AuFile
from hachoir_py2.parser.audio.itunesdb import ITunesDBFile
from hachoir_py2.parser.audio.ipod_playcounts import PlayCountFile
from hachoir_py2.parser.audio.midi import MidiFile
from hachoir_py2.parser.audio.mpeg_audio import MpegAudioFile
from hachoir_py2.parser.audio.real_audio import RealAudioFile
from hachoir_py2.parser.audio.xm import XMModule
from hachoir_py2.parser.audio.s3m import S3MModule
from hachoir_py2.parser.audio.s3m import PTMModule
from hachoir_py2.parser.audio.mod import AmigaModule
from hachoir_py2.parser.audio.flac import FlacParser
