from . import shim
from _typeshed import Incomplete

__all__ = ['GNTPRegister', 'GNTPNotice', 'GNTPSubscribe', 'GNTPOK', 'GNTPError', 'parse_gntp']

class _GNTPBuffer(shim.StringIO):
    def writeln(self, value=None) -> None: ...
    def writeheader(self, key, value) -> None: ...

class _GNTPBase:
    info: Incomplete
    hash_algo: Incomplete
    headers: Incomplete
    resources: Incomplete
    def __init__(self, messagetype=None, version: str = '1.0', encryption=None) -> None: ...
    def __str__(self) -> str: ...
    def _parse_info(self, data): ...
    password: Incomplete
    encryptAlgo: Incomplete
    def set_password(self, password, encryptAlgo: str = 'MD5') -> None: ...
    def _decode_hex(self, value): ...
    def _decode_binary(self, rawIdentifier, identifier): ...
    key: Incomplete
    def _validate_password(self, password): ...
    def validate(self) -> None: ...
    def _format_info(self): ...
    def _parse_dict(self, data): ...
    def add_header(self, key, value) -> None: ...
    def add_resource(self, data): ...
    raw: Incomplete
    def decode(self, data, password=None) -> None: ...
    def encode(self): ...

class GNTPRegister(_GNTPBase):
    _requiredHeaders: Incomplete
    _requiredNotificationHeaders: Incomplete
    notifications: Incomplete
    def __init__(self, data=None, password=None) -> None: ...
    def validate(self) -> None: ...
    raw: Incomplete
    info: Incomplete
    headers: Incomplete
    def decode(self, data, password) -> None: ...
    def add_notification(self, name, enabled: bool = True) -> None: ...
    def encode(self): ...

class GNTPNotice(_GNTPBase):
    _requiredHeaders: Incomplete
    def __init__(self, data=None, app=None, name=None, title=None, password=None) -> None: ...
    raw: Incomplete
    info: Incomplete
    headers: Incomplete
    def decode(self, data, password) -> None: ...

class GNTPSubscribe(_GNTPBase):
    _requiredHeaders: Incomplete
    def __init__(self, data=None, password=None) -> None: ...

class GNTPOK(_GNTPBase):
    _requiredHeaders: Incomplete
    def __init__(self, data=None, action=None) -> None: ...

class GNTPError(_GNTPBase):
    _requiredHeaders: Incomplete
    def __init__(self, data=None, errorcode=None, errordesc=None) -> None: ...
    def error(self): ...

def parse_gntp(data, password=None): ...
