from _typeshed import Incomplete

__all__ = ['mini', 'GrowlNotifier']

class GrowlNotifier:
    passwordHash: str
    socketTimeout: int
    applicationName: Incomplete
    notifications: Incomplete
    defaultNotifications: Incomplete
    applicationIcon: Incomplete
    password: Incomplete
    hostname: Incomplete
    port: Incomplete
    def __init__(self, applicationName: str = 'Python GNTP', notifications=[], defaultNotifications=None, applicationIcon=None, hostname: str = 'localhost', password=None, port: int = 23053) -> None: ...
    def _checkIcon(self, data): ...
    def register(self): ...
    def notify(self, noteType, title, description, icon=None, sticky: bool = False, priority=None, callback=None, identifier=None, custom={}): ...
    def subscribe(self, id, name, port): ...
    def add_origin_info(self, packet) -> None: ...
    def register_hook(self, packet) -> None: ...
    def notify_hook(self, packet) -> None: ...
    def subscribe_hook(self, packet) -> None: ...
    def _send(self, messagetype, packet): ...

def mini(description, applicationName: str = 'PythonMini', noteType: str = 'Message', title: str = 'Mini Message', applicationIcon=None, hostname: str = 'localhost', password=None, port: int = 23053, sticky: bool = False, priority=None, callback=None, notificationIcon=None, identifier=None, notifierFactory=...): ...
