# encoding:utf-8
# author:dbr/Ben
# project:tvdb_api
# repository:http://github.com/dbr/tvdb_api
# license:unlicense (http://unlicense.org/)

"""Custom exceptions used or raised by tvdb_api
"""

__author__ = 'dbr/Ben'
__version__ = '1.9'

__all__ = ['TvdbException', 'TvdbError', 'TvdbUserabort', 'TvdbShownotfound',
           'TvdbSeasonnotfound', 'TvdbEpisodenotfound', 'TvdbAttributenotfound', 'TvdbTokenexpired']


class TvdbException(Exception):
    """Any exception generated by tvdb_api
    """
    pass


class TvdbError(TvdbException):
    """An error with thetvdb.com (Cannot connect, for example)
    """
    pass


class TvdbUserabort(TvdbException):
    """User aborted the interactive selection (via
    the q command, ^c etc)
    """
    pass


class TvdbShownotfound(TvdbException):
    """Show cannot be found on thetvdb.com (non-existant show)
    """
    pass


class TvdbSeasonnotfound(TvdbException):
    """Season cannot be found on thetvdb.com
    """
    pass


class TvdbEpisodenotfound(TvdbException):
    """Episode cannot be found on thetvdb.com
    """
    pass


class TvdbAttributenotfound(TvdbException):
    """Raised if an episode does not have the requested
    attribute (such as a episode name)
    """
    pass


class TvdbTokenexpired(TvdbException):
    """token expired or missing thetvdb.com
    """
    pass
