from ..datetimes import _parse_date as _parse_date
from ..urls import make_safe_absolute_uri as make_safe_absolute_uri
from ..util import FeedParserDict as FeedParserDict
from typing import Any

class Namespace:
    supported_namespaces: Any = ...
    version: Any = ...
    def _start_rss(self, attrs_d: Any) -> None: ...
    infeed: int = ...
    def _start_channel(self, attrs_d: Any) -> None: ...
    def _cdf_common(self, attrs_d: Any) -> None: ...
    def _start_feed(self, attrs_d: Any) -> None: ...
    def _end_channel(self) -> None: ...
    _end_feed: Any = ...
    inimage: int = ...
    title_depth: int = ...
    def _start_image(self, attrs_d: Any) -> None: ...
    def _end_image(self) -> None: ...
    intextinput: int = ...
    def _start_textinput(self, attrs_d: Any) -> None: ...
    _start_textInput: Any = ...
    def _end_textinput(self) -> None: ...
    _end_textInput: Any = ...
    inauthor: int = ...
    def _start_author(self, attrs_d: Any) -> None: ...
    _start_managingeditor: Any = ...
    def _end_author(self) -> None: ...
    _end_managingeditor: Any = ...
    incontributor: int = ...
    def _start_contributor(self, attrs_d: Any) -> None: ...
    def _end_contributor(self) -> None: ...
    def _start_name(self, attrs_d: Any) -> None: ...
    def _end_name(self) -> None: ...
    def _start_width(self, attrs_d: Any) -> None: ...
    def _end_width(self) -> None: ...
    def _start_height(self, attrs_d: Any) -> None: ...
    def _end_height(self) -> None: ...
    def _start_url(self, attrs_d: Any) -> None: ...
    _start_homepage: Any = ...
    _start_uri: Any = ...
    def _end_url(self) -> None: ...
    _end_homepage: Any = ...
    _end_uri: Any = ...
    def _start_email(self, attrs_d: Any) -> None: ...
    def _end_email(self) -> None: ...
    def _start_subtitle(self, attrs_d: Any) -> None: ...
    _start_tagline: Any = ...
    def _end_subtitle(self) -> None: ...
    _end_tagline: Any = ...
    def _start_rights(self, attrs_d: Any) -> None: ...
    _start_copyright: Any = ...
    def _end_rights(self) -> None: ...
    _end_copyright: Any = ...
    inentry: int = ...
    guidislink: int = ...
    def _start_item(self, attrs_d: Any) -> None: ...
    _start_entry: Any = ...
    def _end_item(self) -> None: ...
    _end_entry: Any = ...
    def _start_language(self, attrs_d: Any) -> None: ...
    lang: Any = ...
    def _end_language(self) -> None: ...
    def _start_webmaster(self, attrs_d: Any) -> None: ...
    def _end_webmaster(self) -> None: ...
    def _start_published(self, attrs_d: Any) -> None: ...
    _start_issued: Any = ...
    _start_pubdate: Any = ...
    def _end_published(self) -> None: ...
    _end_issued: Any = ...
    _end_pubdate: Any = ...
    def _start_updated(self, attrs_d: Any) -> None: ...
    _start_modified: Any = ...
    _start_lastbuilddate: Any = ...
    def _end_updated(self) -> None: ...
    _end_modified: Any = ...
    _end_lastbuilddate: Any = ...
    def _start_created(self, attrs_d: Any) -> None: ...
    def _end_created(self) -> None: ...
    def _start_expirationdate(self, attrs_d: Any) -> None: ...
    def _end_expirationdate(self) -> None: ...
    def _start_category(self, attrs_d: Any) -> None: ...
    _start_keywords: Any = ...
    def _end_category(self) -> None: ...
    _end_keywords: Any = ...
    def _start_cloud(self, attrs_d: Any) -> None: ...
    def _start_link(self, attrs_d: Any) -> None: ...
    def _end_link(self) -> None: ...
    def _start_guid(self, attrs_d: Any) -> None: ...
    _start_id: Any = ...
    def _end_guid(self) -> None: ...
    _end_id: Any = ...
    def _start_title(self, attrs_d: Any): ...
    def _end_title(self) -> None: ...
    _summaryKey: str = ...
    def _start_description(self, attrs_d: Any) -> None: ...
    def _start_abstract(self, attrs_d: Any) -> None: ...
    def _end_description(self) -> None: ...
    _end_abstract: Any = ...
    def _start_info(self, attrs_d: Any) -> None: ...
    _start_feedburner_browserfriendly: Any = ...
    def _end_info(self) -> None: ...
    _end_feedburner_browserfriendly: Any = ...
    def _start_generator(self, attrs_d: Any) -> None: ...
    def _end_generator(self) -> None: ...
    def _start_summary(self, attrs_d: Any) -> None: ...
    def _end_summary(self) -> None: ...
    def _start_enclosure(self, attrs_d: Any) -> None: ...
    insource: int = ...
    def _start_source(self, attrs_d: Any) -> None: ...
    def _end_source(self) -> None: ...
    def _start_content(self, attrs_d: Any) -> None: ...
    def _start_body(self, attrs_d: Any) -> None: ...
    _start_xhtml_body: Any = ...
    def _start_content_encoded(self, attrs_d: Any) -> None: ...
    _start_fullitem: Any = ...
    def _end_content(self) -> None: ...
    _end_body: Any = ...
    _end_xhtml_body: Any = ...
    _end_content_encoded: Any = ...
    _end_fullitem: Any = ...
    def _start_newlocation(self, attrs_d: Any) -> None: ...
    def _end_newlocation(self) -> None: ...
