from ..util import FeedParserDict as FeedParserDict
from typing import Any

class Namespace:
    supported_namespaces: Any = ...
    def _start_admin_generatoragent(self, attrs_d: Any) -> None: ...
    def _start_admin_errorreportsto(self, attrs_d: Any) -> None: ...
