from ..datetimes import _parse_date as _parse_date
from ..util import FeedParserDict as FeedParserDict
from typing import Any

class Namespace:
    supported_namespaces: Any = ...
    def _end_dc_author(self) -> None: ...
    def _end_dc_creator(self) -> None: ...
    def _end_dc_date(self) -> None: ...
    def _end_dc_description(self) -> None: ...
    def _end_dc_language(self) -> None: ...
    def _end_dc_publisher(self) -> None: ...
    def _end_dc_rights(self) -> None: ...
    def _end_dc_subject(self) -> None: ...
    def _end_dc_title(self) -> None: ...
    def _end_dcterms_created(self) -> None: ...
    def _end_dcterms_issued(self) -> None: ...
    def _end_dcterms_modified(self) -> None: ...
    def _start_dc_author(self, attrs_d: Any) -> None: ...
    def _start_dc_creator(self, attrs_d: Any) -> None: ...
    def _start_dc_date(self, attrs_d: Any) -> None: ...
    def _start_dc_description(self, attrs_d: Any) -> None: ...
    def _start_dc_language(self, attrs_d: Any) -> None: ...
    def _start_dc_publisher(self, attrs_d: Any) -> None: ...
    def _start_dc_rights(self, attrs_d: Any) -> None: ...
    def _start_dc_subject(self, attrs_d: Any) -> None: ...
    def _start_dc_title(self, attrs_d: Any) -> None: ...
    def _start_dcterms_created(self, attrs_d: Any) -> None: ...
    def _start_dcterms_issued(self, attrs_d: Any) -> None: ...
    def _start_dcterms_modified(self, attrs_d: Any) -> None: ...
    def _start_dcterms_valid(self, attrs_d: Any) -> None: ...
    def _end_dcterms_valid(self) -> None: ...
    incontributor: int = ...
    def _start_dc_contributor(self, attrs_d: Any) -> None: ...
    def _end_dc_contributor(self) -> None: ...
