from ..util import FeedParserDict as FeedParserDict
from typing import Any

class Namespace:
    supported_namespaces: Any = ...
    def _start_itunes_author(self, attrs_d: Any) -> None: ...
    def _end_itunes_author(self) -> None: ...
    def _end_itunes_category(self) -> None: ...
    def _start_itunes_name(self, attrs_d: Any) -> None: ...
    def _end_itunes_name(self) -> None: ...
    def _start_itunes_email(self, attrs_d: Any) -> None: ...
    def _end_itunes_email(self) -> None: ...
    def _start_itunes_subtitle(self, attrs_d: Any) -> None: ...
    def _end_itunes_subtitle(self) -> None: ...
    def _start_itunes_summary(self, attrs_d: Any) -> None: ...
    def _end_itunes_summary(self) -> None: ...
    inpublisher: int = ...
    def _start_itunes_owner(self, attrs_d: Any) -> None: ...
    def _end_itunes_owner(self) -> None: ...
    def _end_itunes_keywords(self) -> None: ...
    def _start_itunes_category(self, attrs_d: Any) -> None: ...
    def _start_itunes_image(self, attrs_d: Any) -> None: ...
    _start_itunes_link: Any = ...
    def _end_itunes_block(self) -> None: ...
    def _end_itunes_explicit(self) -> None: ...
