from ..util import FeedParserDict as FeedParserDict
from typing import Any

class Namespace:
    supported_namespaces: Any = ...
    def _start_media_category(self, attrs_d: Any) -> None: ...
    def _end_media_category(self) -> None: ...
    def _end_media_keywords(self) -> None: ...
    def _start_media_title(self, attrs_d: Any) -> None: ...
    title_depth: Any = ...
    def _end_media_title(self) -> None: ...
    def _start_media_group(self, attrs_d: Any) -> None: ...
    def _start_media_rating(self, attrs_d: Any) -> None: ...
    def _end_media_rating(self) -> None: ...
    def _start_media_credit(self, attrs_d: Any) -> None: ...
    def _end_media_credit(self) -> None: ...
    def _start_media_description(self, attrs_d: Any) -> None: ...
    def _end_media_description(self) -> None: ...
    def _start_media_restriction(self, attrs_d: Any) -> None: ...
    def _end_media_restriction(self) -> None: ...
    def _start_media_license(self, attrs_d: Any) -> None: ...
    def _end_media_license(self) -> None: ...
    def _start_media_content(self, attrs_d: Any) -> None: ...
    def _start_media_thumbnail(self, attrs_d: Any) -> None: ...
    def _end_media_thumbnail(self) -> None: ...
    def _start_media_player(self, attrs_d: Any) -> None: ...
    def _end_media_player(self) -> None: ...
