from .. import util as util
from typing import Any

class Namespace:
    supported_namespaces: Any = ...
    psc_chapters_flag: bool = ...
    def __init__(self) -> None: ...
    def _start_psc_chapters(self, attrs_d: Any) -> None: ...
    def _end_psc_chapters(self) -> None: ...
    def _start_psc_chapter(self, attrs_d: Any) -> None: ...

format_: Any

def _parse_psc_chapter_start(start: Any): ...
