alpha3_to_alpha2 = {
    "afg": "af", "ala": "ax", "alb": "al", "dza": "dz", "asm": "as", "and": "ad", "ago": "ao", "aia": "ai", "ata": "aq",
    "atg": "ag", "arg": "ar", "arm": "am", "abw": "aw", "aus": "au", "aut": "at", "aze": "az", "bhs": "bs", "bhr": "bh",
    "bgd": "bd", "brb": "bb", "blr": "by", "bel": "be", "blz": "bz", "ben": "bj", "bmu": "bm", "btn": "bt", "bol": "bo",
    "bih": "ba", "bwa": "bw", "bvt": "bv", "bra": "br", "vgb": "vg", "iot": "io", "brn": "bn", "bgr": "bg", "bfa": "bf",
    "bdi": "bi", "khm": "kh", "cmr": "cm", "can": "ca", "cpv": "cv", "cym": "ky", "caf": "cf", "tcd": "td", "chl": "cl",
    "chn": "cn", "hkg": "hk", "mac": "mo", "cxr": "cx", "cck": "cc", "col": "co", "com": "km", "cog": "cg", "cod": "cd",
    "cok": "ck", "cri": "cr", "civ": "ci", "hrv": "hr", "cub": "cu", "cyp": "cy", "cze": "cz", "dnk": "dk", "dji": "dj",
    "dma": "dm", "dom": "do", "ecu": "ec", "egy": "eg", "slv": "sv", "gnq": "gq", "eri": "er", "est": "ee", "eth": "et",
    "flk": "fk", "fro": "fo", "fji": "fj", "fin": "fi", "fra": "fr", "guf": "gf", "pyf": "pf", "atf": "tf", "gab": "ga",
    "gmb": "gm", "geo": "ge", "deu": "de", "gha": "gh", "gib": "gi", "grc": "gr", "grl": "gl", "grd": "gd", "glp": "gp",
    "gum": "gu", "gtm": "gt", "ggy": "gg", "gin": "gn", "gnb": "gw", "guy": "gy", "hti": "ht", "hmd": "hm", "vat": "va",
    "hnd": "hn", "hun": "hu", "isl": "is", "ind": "in", "idn": "id", "irn": "ir", "irq": "iq", "irl": "ie", "imn": "im",
    "isr": "il", "ita": "it", "jam": "jm", "jpn": "jp", "jey": "je", "jor": "jo", "kaz": "kz", "ken": "ke", "kir": "ki",
    "prk": "kp", "kor": "kr", "kwt": "kw", "kgz": "kg", "lao": "la", "lva": "lv", "lbn": "lb", "lso": "ls", "lbr": "lr",
    "lby": "ly", "lie": "li", "ltu": "lt", "lux": "lu", "mkd": "mk", "mdg": "mg", "mwi": "mw", "mys": "my", "mdv": "mv",
    "mli": "ml", "mlt": "mt", "mhl": "mh", "mtq": "mq", "mrt": "mr", "mus": "mu", "myt": "yt", "mex": "mx", "fsm": "fm",
    "mda": "md", "mco": "mc", "mng": "mn", "mne": "me", "msr": "ms", "mar": "ma", "moz": "mz", "mmr": "mm", "nam": "na",
    "nru": "nr", "npl": "np", "nld": "nl", "ant": "an", "ncl": "nc", "nzl": "nz", "nic": "ni", "ner": "ne", "nga": "ng",
    "niu": "nu", "nfk": "nf", "mnp": "mp", "nor": "no", "omn": "om", "pak": "pk", "plw": "pw", "pse": "ps", "pan": "pa",
    "png": "pg", "pry": "py", "per": "pe", "phl": "ph", "pcn": "pn", "pol": "pl", "prt": "pt", "pri": "pr", "qat": "qa",
    "reu": "re", "rou": "ro", "rus": "ru", "rwa": "rw", "blm": "bl", "shn": "sh", "kna": "kn", "lca": "lc", "maf": "mf",
    "spm": "pm", "vct": "vc", "wsm": "ws", "smr": "sm", "stp": "st", "sau": "sa", "sen": "sn", "srb": "rs", "syc": "sc",
    "sle": "sl", "sgp": "sg", "svk": "sk", "svn": "si", "slb": "sb", "som": "so", "zaf": "za", "sgs": "gs", "ssd": "ss",
    "esp": "es", "lka": "lk", "sdn": "sd", "sur": "sr", "sjm": "sj", "swz": "sz", "swe": "se", "che": "ch", "syr": "sy",
    "twn": "tw", "tjk": "tj", "tza": "tz", "tha": "th", "tls": "tl", "tgo": "tg", "tkl": "tk", "ton": "to", "tto": "tt",
    "tun": "tn", "tur": "tr", "tkm": "tm", "tca": "tc", "tuv": "tv", "uga": "ug", "ukr": "ua", "are": "ae", "gbr": "gb",
    "usa": "us", "umi": "um", "ury": "uy", "uzb": "uz", "vut": "vu", "ven": "ve", "vnm": "vn", "vir": "vi", "wlf": "wf",
    "esh": "eh", "yem": "ye", "zmb": "zm", "zwe": "zw",
    # non-standard code on imdb for west germany
    'xwg': 'de',
}
lang_to_country = {
    "aa": "dj",
    "af": "za",
    "ak": "gh",
    "sq": "al",
    "am": "et",
    # "ar": "aa",
    "cmn": "cn",
    "hy": "am",
    # "ay": "wh",
    "az": "az",
    "bm": "ml",
    "be": "by",
    "bn": "bd",
    "bi": "vu",
    "bs": "ba",
    "bg": "bg",
    "my": "mm",
    "ca": "ad",
    "zh": "cn",
    "hr": "hr",
    "cs": "cz",
    "da": "dk",
    "dv": "mv",
    "nl": "nl",
    "dz": "bt",
    "en": "gb",
    "et": "ee",
    # "ee": "ew",
    "fj": "fj",
    "fil": "ph",
    "fi": "fi",
    "fr": "fr",
    # "ff": "ff",
    "gaa": "gh",
    "ka": "ge",
    "de": "de",
    "el": "gr",
    # "gn": "gx",
    "gu": "in",
    "ht": "ht",
    # "ha": "ha",
    "he": "il",
    "hi": "in",
    "ho": "pg",
    "hu": "hu",
    "is": "is",
    "ig": "ng",
    "id": "id",
    "ga": "ie",
    "it": "it",
    "ja": "jp",
    "kr": "ne",
    "kk": "kz",
    "km": "kh",
    "kmb": "ao",
    "rw": "rw",
    "kg": "cg",
    "ko": "kr",
    "kj": "ao",
    "ku": "iq",
    "ky": "kg",
    "lo": "la",
    "la": "va",
    "lv": "lv",
    "ln": "cg",
    "lt": "lt",
    "lu": "cd",
    "lb": "lu",
    "mk": "mk",
    "mg": "mg",
    "ms": "my",
    "mt": "mt",
    "mi": "nz",
    "mh": "mh",
    "mn": "mn",
    "mos": "bf",
    "ne": "np",
    "nd": "zw",
    "nso": "za",
    "no": "no",
    "nb": "no",
    "nn": "no",
    "ny": "mw",
    "pap": "aw",
    "ps": "af",
    "fa": "ir",
    "pl": "pl",
    "pt": "pt",
    "pa": "in",
    # "qu": "wh",
    "ro": "ro",
    "rm": "ch",
    "rn": "bi",
    "ru": "ru",
    "sg": "cf",
    "sr": "rs",
    "srr": "sn",
    "sn": "zw",
    "si": "lk",
    "sk": "sk",
    "sl": "si",
    "so": "so",
    "snk": "sn",
    "nr": "za",
    "st": "ls",
    "es": "es",
    # "sw": "sw",
    "ss": "sz",
    "sv": "se",
    "tl": "ph",
    "tg": "tj",
    "ta": "lk",
    "te": "in",
    "tet": "tl",
    "th": "th",
    "ti": "er",
    "tpi": "pg",
    "ts": "za",
    "tn": "bw",
    "tr": "tr",
    "tk": "tm",
    "uk": "ua",
    "umb": "ao",
    "ur": "pk",
    "uz": "uz",
    "ve": "za",
    "vi": "vn",
    "cy": "gb-wls",
    "wo": "sn",
    "xh": "za",
    # "yo": "yo",
    "zu": "za",
    # auto mapped
    'gv': 'im',
    'kl': 'gl',
    'oc': 'ad',
    'ar': 'ye',
    'ay': 'bo',
    'ff': 'gn',
    'gn': 'py',
    'qu': 'bo',
    'sw': 'ug',
    # auto matched json
    'av': 'tr',
    'bho': 'mu',
    'ce': 'ru',
    'ee': 'tg',
    'ha': 'tg',
    'hz': 'na',
    'iu': 'ca',
    'jv': 'sr',
    'ks': 'in',
    'kv': 'ru',
    'lg': 'ug',
    'or': 'in',
    'ty': 'pf',
    'yo': 'ng',
    'yue': 'hk',
    # manually matched
    'ab': 'Republic_of_Abkhazia',
    'eo': 'Esperanto',
    'fy': 'nl',
    'ia': 'Interlingua',
    'ii': 'cn',
    'ik': 'Alaska',
    'nv': 'Navajo_Nation',
    'oj': 'us',
    'os': 'ru',
    'pi': 'in',
    'sr-latn': 'rs',
    'su': 'id',
    'vo': 'Volapuk',
    'wa': 'be',
    'yi': 'Jewish_Autonomous_Oblast',
    'an': 'Aragon',
    # sign languages
    'gsg': 'de',
    'ase': 'us',
    # unknown codes
    # 'qbo': '',
}