"""Custom exceptions used or raised by imdb_api
"""

__author__ = 'Prinz23'
__version__ = '1.0'

__all__ = ['IMDbException', 'IMDbError', 'IMDbUserabort', 'IMDbShownotfound',
           'IMDbSeasonnotfound', 'IMDbEpisodenotfound', 'IMDbAttributenotfound', 'IMDbTokenexpired',
           'IMDbPersonNotFound']

from lib.tvinfo_base.exceptions import *


class IMDbException(BaseTVinfoException):
    """Any exception generated by imdb_api
    """
    pass


class IMDbError(BaseTVinfoError, IMDbException):
    """An error with imdb.com (Cannot connect, for example)
    """
    pass


class IMDbUserabort(BaseTVinfoUserabort, IMDbError):
    """User aborted the interactive selection (via
    the q command, ^c etc)
    """
    pass


class IMDbShownotfound(BaseTVinfoShownotfound, IMDbError):
    """Show cannot be found on imdb.com (non-existant show)
    """
    pass


class IMDbSeasonnotfound(BaseTVinfoSeasonnotfound, IMDbError):
    """Season cannot be found on imdb.com
    """
    pass


class IMDbEpisodenotfound(BaseTVinfoEpisodenotfound, IMDbError):
    """Episode cannot be found on imdb.com
    """
    pass


class IMDbAttributenotfound(BaseTVinfoAttributenotfound, IMDbError):
    """Raised if an episode does not have the requested
    attribute (such as a episode name)
    """
    pass


class IMDbTokenexpired(BaseTVinfoAuthenticationerror, IMDbError):
    """token expired or missing imdb.com
    """
    pass


class IMDbPersonNotFound(BaseTVinfoPersonNotFound, IMDbError):
    """person id notfound at imdb.com
    """
    pass
