class ThingsNobodyCaresAboutButMe(Exception): ...
class CharacterEncodingOverride(ThingsNobodyCaresAboutButMe): ...
class CharacterEncodingUnknown(ThingsNobodyCaresAboutButMe): ...
class NonXMLContentType(ThingsNobodyCaresAboutButMe): ...
class UndeclaredNamespace(Exception): ...
