import sgmllib as sgmllib
from typing import Any

_SGML_AVAILABLE: int

class sgmllib:
    SGMLParseError: Any = ...
    class SGMLParser:
        lasttag: Any = ...
        rawdata: Any = ...
        def close(self) -> None: ...
        def feed(self, data: Any) -> None: ...
        def goahead(self, i: Any) -> None: ...
        def parse_declaration(self, i: Any) -> None: ...
        def parse_starttag(self, i: Any) -> None: ...
        def reset(self) -> None: ...

charref: Any
tagfind: Any
attrfind: Any
entityref: Any
incomplete: Any
interesting: Any
shorttag: Any
shorttagopen: Any
starttagopen: Any

class _EndBracketRegEx:
    endbracket: Any = ...
    def __init__(self) -> None: ...
    def search(self, target: Any, index: int = ...): ...

class EndBracketMatch:
    match: Any = ...
    def __init__(self, match: Any) -> None: ...
    def start(self, n: Any): ...

endbracket: Any
