from .html import _BaseHTMLProcessor as _BaseHTMLProcessor
from typing import Any, Optional

ACCEPTABLE_URI_SCHEMES: Any
_urifixer: Any

def _urljoin(base: Any, uri: Any): ...
def convert_to_idn(url: Any): ...
def make_safe_absolute_uri(base: Any, rel: Optional[Any] = ...): ...

class RelativeURIResolver(_BaseHTMLProcessor):
    relative_uris: Any = ...
    baseuri: Any = ...
    def __init__(self, baseuri: Any, encoding: Any, _type: Any) -> None: ...
    def resolve_uri(self, uri: Any): ...
    def unknown_starttag(self, tag: Any, attrs: Any) -> None: ...

def resolve_relative_uris(html_source: Any, base_uri: Any, encoding: Any, type_: Any): ...
