from typing import Any, Optional

class FeedParserDict(dict):
    keymap: Any = ...
    def __getitem__(self, key: Any): ...
    def __contains__(self, key: Any): ...
    has_key: Any = ...
    def get(self, key: Any, default: Optional[Any] = ...): ...
    def __setitem__(self, key: Any, value: Any): ...
    def setdefault(self, k: Any, default: Any): ...
    def __getattr__(self, key: Any): ...
    def __hash__(self) -> Any: ...
