from ...apprise_attachment import AppriseAttachment as AppriseAttachment
from ...asset import AppriseAsset as AppriseAsset
from ...exception import AppriseInvalidData as AppriseInvalidData
from ...utils.base64 import base64_urldecode as base64_urldecode
from _typeshed import Incomplete
from cryptography.hazmat.primitives.asymmetric import ec

CRYPTOGRAPHY_SUPPORT: bool

class WebPushSubscription:
    __endpoint: Incomplete
    __p256dh: Incomplete
    __auth: Incomplete
    __auth_secret: Incomplete
    __public_key: Incomplete
    def __init__(self, content: str | dict | None = None) -> None: ...
    def load(self, content: str | dict | None = None) -> bool: ...
    def write(self, path: str, indent: int = 2) -> bool: ...
    @property
    def auth(self) -> str | None: ...
    @property
    def endpoint(self) -> str | None: ...
    @property
    def p256dh(self) -> str | None: ...
    @property
    def auth_secret(self) -> bytes | None: ...
    @property
    def public_key(self) -> ec.EllipticCurvePublicKey | None: ...
    @property
    def dict(self) -> dict: ...
    def json(self, indent: int = 2) -> str: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...

class WebPushSubscriptionManager:
    max_load_failure_count: int
    __subscriptions: Incomplete
    asset: Incomplete
    def __init__(self, asset: AppriseAsset | None = None) -> None: ...
    def __getitem__(self, key: str) -> WebPushSubscription: ...
    def __setitem__(self, name: str, subscription: WebPushSubscription | str | dict) -> None: ...
    def add(self, subscription: WebPushSubscription | str | dict, name: str | None = None) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iadd__(self, subscription: WebPushSubscription | str | dict) -> WebPushSubscriptionManager: ...
    def __contains__(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    @property
    def dict(self) -> dict: ...
    def load(self, path: str, byte_limit: int = 0) -> bool: ...
    def write(self, path: str, indent: int = 2) -> bool: ...
    def json(self, indent: int = 2) -> str: ...
