from tornado_py3 import gen as gen
from tornado_py3.concurrent import Future as Future
from tornado_py3.ioloop import IOLoop as IOLoop
from tornado_py3.netutil import Resolver as Resolver, is_valid_ip as is_valid_ip
from typing import Any, Generator, List, Tuple

class CaresResolver(Resolver):
    io_loop: Any = ...
    channel: Any = ...
    fds: Any = ...
    def initialize(self) -> None: ...
    def resolve(self, host: str, port: int, family: int=...) -> Generator[Any, Any, List[Tuple[int, Any]]]: ...
