from tornado_py3 import gen as gen
from tornado_py3.concurrent import Future as Future, future_set_exc_info as future_set_exc_info
from tornado_py3.escape import utf8 as utf8
from tornado_py3.netutil import Resolver as Resolver
from typing import Any, Generator, List, Tuple

class TwistedResolver(Resolver):
    reactor: Any = ...
    resolver: Any = ...
    def initialize(self) -> None: ...
    def resolve(self, host: str, port: int, family: int=...) -> Generator[Any, Any, List[Tuple[int, Any]]]: ...
