# Stubs for tornado_py3.platform.windows (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SetHandleInformation: Any
HANDLE_FLAG_INHERIT: int

def set_close_exec(fd: int) -> None: ...
