from .. import common as common, plugins as plugins
from ..asset import AppriseAsset as AppriseAsset
from ..manager_config import ConfigurationManager as ConfigurationManager
from ..manager_plugins import NotificationManager as NotificationManager
from ..url import URLBase as URLBase
from ..utils.cwe312 import cwe312_url as cwe312_url
from ..utils.parse import GET_SCHEMA_RE as GET_SCHEMA_RE, parse_bool as parse_bool, parse_list as parse_list, parse_urls as parse_urls
from ..utils.time import zoneinfo as zoneinfo
from _typeshed import Incomplete

VALID_TOKEN: Incomplete
N_MGR: Incomplete
C_MGR: Incomplete

class ConfigBase(URLBase):
    encoding: str
    default_config_format: Incomplete
    config_format: Incomplete
    max_buffer_size: int
    allow_cross_includes: Incomplete
    config_path: Incomplete
    _cached_time: Incomplete
    _cached_servers: Incomplete
    recursion: Incomplete
    insecure_includes: Incomplete
    cache: Incomplete
    def __init__(self, cache: bool | int = True, recursion: int = 0, insecure_includes: bool = False, **kwargs: object) -> None: ...
    def servers(self, asset: AppriseAsset | None = None, **kwargs: object) -> list[plugins.NotifyBase]: ...
    def read(self) -> str | None: ...
    def expired(self) -> bool: ...
    @staticmethod
    def __normalize_tag_groups(group_tags: dict[str, set[str]]) -> None: ...
    @staticmethod
    def parse_url(url: str, verify_host: bool = True) -> dict[str, object] | None: ...
    @staticmethod
    def detect_config_format(content: str, **kwargs: object) -> common.ConfigFormat | None: ...
    @staticmethod
    def config_parse(content: str, asset: AppriseAsset | None = None, config_format: str | common.ConfigFormat | None = None, **kwargs: object) -> tuple[list[object], list[str]]: ...
    @staticmethod
    def config_parse_text(content: str, asset: AppriseAsset | None = None) -> tuple[list[object], list[str]]: ...
    def pop(self, index: int = -1) -> object: ...
    @staticmethod
    def _special_token_handler(schema: str, tokens: dict[str, object]) -> dict[str, object]: ...
    def __getitem__(self, index: int) -> object: ...
    def __iter__(self) -> object: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
