from . import __version__ as __version__, common as common, plugins as plugins
from .apprise_attachment import AppriseAttachment as AppriseAttachment
from .apprise_config import AppriseConfig as AppriseConfig
from .asset import AppriseAsset as AppriseAsset
from .common import ContentLocation as ContentLocation
from .config.base import ConfigBase as ConfigBase
from .conversion import convert_between as convert_between
from .emojis import apply_emojis as apply_emojis
from .locale import AppriseLocale as AppriseLocale
from .logger import logger as logger
from .manager_plugins import NotificationManager as NotificationManager
from .plugins.base import NotifyBase as NotifyBase
from .utils.cwe312 import cwe312_url as cwe312_url
from .utils.logic import is_exclusive_match as is_exclusive_match
from .utils.parse import parse_list as parse_list, parse_urls as parse_urls
from _typeshed import Incomplete
from collections.abc import Generator, Iterator
from typing import Any

N_MGR: Incomplete

class Apprise:
    servers: Incomplete
    asset: Incomplete
    locale: Incomplete
    debug: Incomplete
    location: Incomplete
    def __init__(self, servers: str | dict | NotifyBase | AppriseConfig | ConfigBase | list[str | dict | NotifyBase | AppriseConfig | ConfigBase] | None = None, asset: AppriseAsset | None = None, location: ContentLocation | None = None, debug: bool = False) -> None: ...
    @staticmethod
    def instantiate(url: str | dict, asset: AppriseAsset | None = None, tag: str | list[str] | None = None, suppress_exceptions: bool = True) -> NotifyBase | None: ...
    def add(self, servers: str | dict | NotifyBase | AppriseConfig | ConfigBase | list[str | dict | NotifyBase | AppriseConfig | ConfigBase], asset: AppriseAsset | None = None, tag: str | list[str] | None = None) -> bool: ...
    def clear(self) -> None: ...
    def find(self, tag: Any = ..., match_always: bool = True) -> Iterator[NotifyBase]: ...
    def notify(self, body: str | bytes, title: str | bytes = '', notify_type: str | common.NotifyType = ..., body_format: str | None = None, tag: Any = ..., match_always: bool = True, attach: Any = None, interpret_escapes: bool | None = None) -> bool | None: ...
    async def async_notify(self, *args: Any, **kwargs: Any) -> bool | None: ...
    def _create_notify_calls(self, *args, **kwargs): ...
    def _create_notify_gen(self, body, title: str = '', notify_type=..., body_format=None, tag=..., match_always: bool = True, attach=None, interpret_escapes=None) -> Generator[Incomplete]: ...
    @staticmethod
    def _notify_sequential(*servers_kwargs): ...
    @staticmethod
    def _notify_parallel_threadpool(*servers_kwargs): ...
    @staticmethod
    async def _notify_parallel_asyncio(*servers_kwargs): ...
    def details(self, lang: str | None = None, show_requirements: bool = False, show_disabled: bool = False) -> dict[str, Any]: ...
    def urls(self, privacy: bool = False) -> list[str]: ...
    def pop(self, index: int) -> NotifyBase: ...
    def __getitem__(self, index: int) -> NotifyBase: ...
    def __getstate__(self) -> dict[str, object]: ...
    def __setstate__(self, state: dict[str, object]) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[NotifyBase]: ...
    def __len__(self) -> int: ...
