from .asset import AppriseAsset as AppriseAsset
from .attachment.base import AttachBase as AttachBase
from .common import ContentLocation as ContentLocation
from .logger import logger as logger
from .manager_attachment import AttachmentManager as AttachmentManager
from .url import URLBase as URLBase
from .utils.parse import GET_SCHEMA_RE as GET_SCHEMA_RE
from _typeshed import Incomplete
from collections.abc import Iterator
from typing import Any

A_MGR: Incomplete

class AppriseAttachment:
    attachments: Incomplete
    cache: Incomplete
    asset: Incomplete
    location: Incomplete
    def __init__(self, paths: str | list[str | AttachBase | AppriseAttachment] | None = None, asset: AppriseAsset | None = None, cache: bool | int = True, location: str | ContentLocation | None = None, **kwargs: Any) -> None: ...
    def add(self, attachments: str | AttachBase | AppriseAttachment | list[str | AttachBase | AppriseAttachment], asset: AppriseAsset | None = None, cache: bool | int | None = None) -> bool: ...
    @staticmethod
    def instantiate(url: str, asset: AppriseAsset | None = None, cache: bool | int | None = None, suppress_exceptions: bool = True) -> AttachBase | None: ...
    def sync(self, abort_on_error: bool = True, abort_if_empty: bool = True) -> bool: ...
    def clear(self) -> None: ...
    def size(self) -> int: ...
    def pop(self, index: int = -1) -> AttachBase: ...
    def __getitem__(self, index: int) -> AttachBase: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[AttachBase]: ...
    def __len__(self) -> int: ...
