from . import common as common
from .asset import AppriseAsset as AppriseAsset
from .config.base import ConfigBase as ConfigBase
from .logger import logger as logger
from .manager_config import ConfigurationManager as ConfigurationManager
from .plugins.base import NotifyBase as NotifyBase
from .url import URLBase as URLBase
from .utils.logic import is_exclusive_match as is_exclusive_match
from .utils.parse import GET_SCHEMA_RE as GET_SCHEMA_RE, parse_list as parse_list
from _typeshed import Incomplete
from typing import Any

C_MGR: Incomplete

class AppriseConfig:
    configs: Incomplete
    asset: Incomplete
    cache: Incomplete
    recursion: Incomplete
    insecure_includes: Incomplete
    def __init__(self, paths: str | list[str] | None = None, asset: AppriseAsset | None = None, cache: bool | int = True, recursion: int = 0, insecure_includes: bool = False, **kwargs: Any) -> None: ...
    def add(self, configs: str | ConfigBase | list[str | ConfigBase], asset: AppriseAsset | None = None, tag: str | list[str] | None = None, cache: bool | int = True, recursion: int | None = None, insecure_includes: bool | None = None) -> bool: ...
    def add_config(self, content: str, asset: AppriseAsset | None = None, tag: str | list[str] | None = None, format: str | None = None, recursion: int | None = None, insecure_includes: bool | None = None) -> bool: ...
    def servers(self, tag: str | list[str] = ..., match_always: bool = True, *args: Any, **kwargs: Any) -> list[NotifyBase]: ...
    @staticmethod
    def instantiate(url: str, asset: AppriseAsset | None = None, tag: str | list[str] | None = None, cache: bool | int | None = None, recursion: int = 0, insecure_includes: bool = False, suppress_exceptions: bool = True) -> ConfigBase | None: ...
    def clear(self) -> None: ...
    def server_pop(self, index: int) -> NotifyBase: ...
    def pop(self, index: int = -1) -> ConfigBase: ...
    def __getitem__(self, index: int) -> ConfigBase: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[ConfigBase]: ...
    def __len__(self) -> int: ...
