from .common import NotifyFormat as NotifyFormat
from .url import URLBase as URLBase
from _typeshed import Incomplete
from collections.abc import Generator
from html.parser import HTMLParser

def convert_between(from_format, to_format, content): ...
def text_to_html(content): ...
def html_to_text(content): ...

class HTMLConverter(HTMLParser):
    BLOCK_TAGS: Incomplete
    IGNORE_TAGS: Incomplete
    WS_TRIM: Incomplete
    BLOCK_END: Incomplete
    _do_store: bool
    _result: Incomplete
    converted: str
    def __init__(self, **kwargs) -> None: ...
    def close(self) -> None: ...
    def _finalize(self, result) -> Generator[Incomplete]: ...
    def handle_data(self, data, *args, **kwargs) -> None: ...
    def handle_starttag(self, tag, attrs) -> None: ...
    def handle_endtag(self, tag) -> None: ...
