from .logger import logger as logger
from .utils.disk import path_decode as path_decode
from .utils.module import import_module as import_module
from .utils.parse import parse_list as parse_list
from .utils.singleton import Singleton as Singleton
from _typeshed import Incomplete
from collections.abc import Generator

class PluginManager(metaclass=Singleton):
    name: str
    _id: str
    module_name_prefix: Incomplete
    module_path: Incomplete
    module_filter_re: Incomplete
    _lock: Incomplete
    _module_map: Incomplete
    _schema_map: Incomplete
    _custom_module_map: Incomplete
    _disabled: Incomplete
    _paths_previously_scanned: Incomplete
    _loaded: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def unload_modules(self, disable_native: bool = False) -> None: ...
    def load_modules(self, path=None, name=None, force: bool = False) -> None: ...
    def module_detection(self, paths, cache: bool = True) -> None: ...
    def add(self, plugin, schemas=None, url=None, send_func=None): ...
    def remove(self, *schemas) -> None: ...
    def plugins(self, include_disabled: bool = True) -> Generator[Incomplete]: ...
    def schemas(self, include_disabled: bool = True): ...
    def disable(self, *schemas) -> None: ...
    def enable_only(self, *schemas) -> None: ...
    def __contains__(self, schema) -> bool: ...
    def __delitem__(self, schema) -> None: ...
    def __setitem__(self, schema, plugin) -> None: ...
    def __getitem__(self, schema): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
