import builtins
import hashlib
import json
from . import exception as exception
from .common import PersistentStoreMode as PersistentStoreMode
from .logger import logger as logger
from .utils.disk import path_decode as path_decode
from _typeshed import Incomplete
from datetime import datetime
from typing import Any

EPOCH: Incomplete
AWARE_DATE_ISO_FORMAT: str
NAIVE_DATE_ISO_FORMAT: str

def _ntf_tidy(ntf) -> None: ...

class CacheObject:
    hash_engine = hashlib.sha256
    hash_length: int
    __value: Incomplete
    __class_name: Incomplete
    __expires: Incomplete
    __persistent: Incomplete
    def __init__(self, value: Any = None, expires: bool | float | int | datetime | None = False, persistent: bool = True) -> None: ...
    def set(self, value: Any, expires: bool | float | int | datetime | None = None, persistent: bool | None = None) -> None: ...
    def set_expiry(self, expires: datetime | bool | float | int | None = None) -> None: ...
    def hash(self) -> str: ...
    def json(self) -> dict[str, Any] | None: ...
    @staticmethod
    def instantiate(content: dict[str, Any], persistent: bool = True, verify: bool = True) -> CacheObject | None: ...
    @property
    def value(self) -> Any: ...
    @property
    def persistent(self) -> bool: ...
    @property
    def expires(self) -> datetime | None: ...
    @property
    def expires_sec(self) -> float | None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __str__(self) -> str: ...

class CacheJSONEncoder(json.JSONEncoder):
    def default(self, entry): ...

class PersistentStore:
    max_file_size: int
    default_file_expiry: int
    encoding: str
    base_key: str
    __cache_key: str
    temp_dir: str
    data_dir: str
    __extension: str
    __backup_extension: str
    __valid_key: Incomplete
    __not_found_ref: Incomplete
    __mode: Incomplete
    __exclude_list: Incomplete
    __renew: Incomplete
    __base_path: Incomplete
    __temp_path: Incomplete
    __data_path: Incomplete
    __dirty: bool
    __cache_size: Incomplete
    __cache_files: Incomplete
    _cache: Incomplete
    def __init__(self, path: str | None = None, namespace: str = 'default', mode: str | PersistentStoreMode | None = None) -> None: ...
    def read(self, key: str | None = None, compress: bool = True, expires: bool | float | int = False) -> bytes | None: ...
    def write(self, data: bytes | str | Any, key: str | None = None, compress: bool = True, _recovery: bool = False) -> bool: ...
    def __move(self, src, dst): ...
    def open(self, key: str | None = None, mode: str = 'r', buffering: int = -1, encoding: str | None = None, errors: str | None = None, newline: str | None = None, closefd: bool = True, opener: Any | None = None, compress: bool = False, compresslevel: int = 9) -> Any: ...
    def get(self, key: str, default: Any = None, lazy: bool = True) -> Any: ...
    def set(self, key: str, value: Any, expires: float | int | datetime | bool | None = None, persistent: bool = True, lazy: bool = True) -> bool: ...
    def clear(self, *args: str) -> bool | None: ...
    def prune(self) -> bool: ...
    def __load_cache(self, _recovery: bool = False): ...
    def __prepare(self, flush: bool = True): ...
    def flush(self, force: bool = False, _recovery: bool = False) -> bool: ...
    def files(self, exclude: bool = True, lazy: bool = True) -> list[str]: ...
    @staticmethod
    def disk_scan(path: str, namespace: str | list[str] | None = None, closest: bool = True) -> list[str]: ...
    @staticmethod
    def disk_prune(path: str, namespace: str | list[str] | None = None, expires: int | float | None = None, action: bool = False) -> dict[str, list[dict[str, str | bool]]]: ...
    def size(self, exclude: bool = True, lazy: bool = True) -> int: ...
    def __del__(self) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def keys(self) -> builtins.set[str]: ...
    def delete(self, *args: str, all: bool | None = None, temp: bool | None = None, cache: bool | None = None, validate: bool = True) -> bool: ...
    @property
    def cache_file(self) -> str: ...
    @property
    def path(self) -> str | None: ...
    @property
    def mode(self) -> PersistentStoreMode: ...
