from .asset import AppriseAsset as AppriseAsset
from .logger import logger as logger
from .utils.parse import parse_bool as parse_bool, parse_list as parse_list, parse_phone_no as parse_phone_no, parse_url as parse_url, urlencode as urlencode
from _typeshed import Incomplete

PATHSPLIT_LIST_DELIM: Incomplete

class PrivacyMode:
    Secret: str
    Outer: str
    Tail: str

HTML_LOOKUP: Incomplete

class URLBase:
    service_name: Incomplete
    protocol: Incomplete
    secure_protocol: Incomplete
    request_rate_per_sec: int
    socket_connect_timeout: float
    socket_read_timeout: float
    url_identifier: Incomplete
    __cached_url_identifier: bool
    tags: Incomplete
    verify_certificate: bool
    logger = logger
    templates: Incomplete
    template_tokens: Incomplete
    template_args: Incomplete
    template_kwargs: Incomplete
    asset: Incomplete
    schema: Incomplete
    secure: Incomplete
    host: Incomplete
    port: Incomplete
    user: Incomplete
    password: Incomplete
    fullpath: Incomplete
    _last_io_datetime: Incomplete
    def __init__(self, asset=None, **kwargs) -> None: ...
    def throttle(self, last_io=None, wait=None) -> None: ...
    def url(self, privacy: bool = False, *args, **kwargs): ...
    def url_id(self, lazy: bool = True, hash_engine=...): ...
    def __contains__(self, tags) -> bool: ...
    def __str__(self) -> str: ...
    @staticmethod
    def escape_html(html, convert_new_lines: bool = False, whitespace: bool = True): ...
    @staticmethod
    def unquote(content, encoding: str = 'utf-8', errors: str = 'replace'): ...
    @staticmethod
    def quote(content, safe: str = '/', encoding=None, errors=None): ...
    @staticmethod
    def pprint(content, privacy: bool = True, mode=..., quote: bool = True, safe: str = '/', encoding=None, errors=None): ...
    @staticmethod
    def urlencode(query, doseq: bool = False, safe: str = '', encoding=None, errors=None): ...
    @staticmethod
    def split_path(path, unquote: bool = True): ...
    @staticmethod
    def parse_list(content, allow_whitespace: bool = True, unquote: bool = True): ...
    @staticmethod
    def parse_phone_no(content, unquote: bool = True, prefix: bool = False): ...
    @property
    def app_id(self): ...
    @property
    def app_desc(self): ...
    @property
    def app_url(self): ...
    @property
    def request_timeout(self): ...
    @property
    def request_auth(self): ...
    @property
    def request_url(self): ...
    def url_parameters(self, *args, **kwargs): ...
    @staticmethod
    def post_process_parse_url_results(results): ...
    @staticmethod
    def parse_url(url, verify_host: bool = True, plus_to_space: bool = False, strict_port: bool = False, sanitize: bool = True): ...
    @staticmethod
    def http_response_code_lookup(code, response_mask=None): ...
    def __len__(self) -> int: ...
    def schemas(self): ...
