from hachoir_py2.parser.image.bmp import BmpFile
from hachoir_py2.parser.image.gif import GifFile
from hachoir_py2.parser.image.ico import IcoFile
from hachoir_py2.parser.image.jpeg import JpegFile
from hachoir_py2.parser.image.pcx import PcxFile
from hachoir_py2.parser.image.psd import PsdFile
from hachoir_py2.parser.image.png import PngFile
from hachoir_py2.parser.image.tga import TargaFile
from hachoir_py2.parser.image.tiff import TiffFile
from hachoir_py2.parser.image.wmf import WMF_File
from hachoir_py2.parser.image.xcf import XcfFile
