def base64_urlencode(data: bytes) -> str: ...
def base64_urldecode(data: str) -> bytes: ...
def decode_b64_dict(di: dict) -> dict: ...
def encode_b64_dict(di: dict, encoding: str = 'utf-8') -> tuple[dict, bool]: ...
