from .disk import tidy_path as tidy_path
from _typeshed import Incomplete

VALID_URL_RE: Incomplete
VALID_QUERY_RE: Incomplete
STRING_DELIMITERS: str
STRING_DELIMITERS_NO_WS: str
NOTIFY_CUSTOM_ADD_TOKENS: Incomplete
NOTIFY_CUSTOM_DEL_TOKENS: Incomplete
NOTIFY_CUSTOM_COLON_TOKENS: Incomplete
GET_SCHEMA_RE: Incomplete
URL_DETAILS_RE: Incomplete
GET_EMAIL_RE: Incomplete
IS_PHONE_NO: Incomplete
PHONE_NO_DETECTION_RE: Incomplete
PHONE_NO_WPREFIX_DETECTION_RE: Incomplete
IS_CALL_SIGN: Incomplete
CALL_SIGN_DETECTION_RE: Incomplete
URL_DETECTION_RE: Incomplete
EMAIL_DETECTION_RE: Incomplete
UUID4_RE: Incomplete
VALID_PYTHON_FILE_RE: Incomplete
REGEX_VALIDATE_LOOKUP: Incomplete

def is_ipaddr(addr, ipv4: bool = True, ipv6: bool = True): ...
def is_hostname(hostname, ipv4: bool = True, ipv6: bool = True, underscore: bool = True): ...
def is_uuid(uuid): ...
def is_phone_no(phone, min_len: int = 10): ...
def is_call_sign(callsign): ...
def is_email(address): ...
def parse_qsd(qs, simple: bool = False, plus_to_space: bool = False, sanitize: bool = True): ...
def parse_url(url, default_schema: str = 'http', verify_host: bool = True, strict_port: bool = False, simple: bool = False, plus_to_space: bool = False, sanitize: bool = True): ...
def parse_bool(arg, default: bool = False): ...
def parse_phone_no(*args, store_unparseable: bool = True, prefix: bool = False, **kwargs): ...
def parse_call_sign(*args, store_unparseable: bool = True, **kwargs): ...
def parse_emails(*args, store_unparseable: bool = True, **kwargs): ...
def url_assembly(encode: bool = False, **kwargs): ...
def urlencode(query, doseq: bool = False, safe: str = '', encoding=None, errors=None): ...
def parse_urls(*args, store_unparseable: bool = True, **kwargs): ...
def parse_list(*args, cast=None, allow_whitespace: bool = True): ...
def validate_regex(value, regex: str = '[^\\s]+', flags=..., strip: bool = True, fmt=None): ...
