from ..apprise_attachment import AppriseAttachment as AppriseAttachment
from ..asset import AppriseAsset as AppriseAsset
from ..exception import ApprisePluginException as ApprisePluginException
from ..logger import logger as logger
from ..utils.base64 import base64_urldecode as base64_urldecode, base64_urlencode as base64_urlencode
from _typeshed import Incomplete
from cryptography.hazmat.primitives.asymmetric import ec

PEM_SUPPORT: bool

class ApprisePEMException(ApprisePluginException):
    def __init__(self, message, error_code: int = 612) -> None: ...

class ApprisePEMController:
    max_pem_public_key_size: int
    max_pem_private_key_size: int
    max_webpush_record_size: int
    path: Incomplete
    __private_key: Incomplete
    __public_key: Incomplete
    name: Incomplete
    asset: Incomplete
    _prv_keyfile: Incomplete
    _pub_keyfile: Incomplete
    def __init__(self, path: str, pub_keyfile: str | None = None, prv_keyfile: str | None = None, name: str | None = None, asset: AppriseAsset | None = None, **kwargs) -> None: ...
    def load_private_key(self, path: str | None = None, *names: str) -> bool: ...
    def load_public_key(self, path: str | None = None, *names: str) -> bool: ...
    def keygen(self, name: str | None = None, force: bool = False): ...
    def public_keyfile(self, *names: str) -> str | None: ...
    def private_keyfile(self, *names: str) -> str | None: ...
    def public_key(self, *names: str, autogen: bool | None = None, autodetect: bool = True) -> ec.EllipticCurvePublicKey | None: ...
    def private_key(self, *names: str, autogen: bool | None = None, autodetect: bool = True) -> ec.EllipticCurvePrivateKey | None: ...
    def encrypt_webpush(self, message: str | bytes, public_key: ec.EllipticCurvePublicKey, auth_secret: bytes) -> bytes: ...
    def encrypt(self, message: str | bytes, public_key: ec.EllipticCurvePublicKey | None = None, salt: bytes | None = None) -> str | None: ...
    def decrypt(self, encrypted_payload: str | bytes, private_key: ec.EllipticCurvePrivateKey | None = None, salt: bytes | None = None) -> str | None: ...
    def sign(self, content: bytes) -> bytes | None: ...
    @property
    def pub_keyfile(self) -> str | bool | None: ...
    @property
    def prv_keyfile(self) -> str | bool | None: ...
    @property
    def x962_str(self) -> str: ...
    def __bool__(self) -> bool: ...
