import types
from .. import exception as exception
from ..common import ContentLocation as ContentLocation
from ..url import URLBase as URLBase
from ..utils.parse import parse_bool as parse_bool
from _typeshed import Incomplete
from collections.abc import Generator

class AttachBase(URLBase):
    max_detect_buffer_size: int
    unknown_mimetype: str
    unknown_filename: str
    unknown_filename_extension: str
    strict: bool
    max_file_size: int
    location: Incomplete
    template_args: Incomplete
    _name: Incomplete
    _mimetype: Incomplete
    detected_mimetype: Incomplete
    detected_name: Incomplete
    download_path: Incomplete
    __pointers: Incomplete
    cache: Incomplete
    def __init__(self, name=None, mimetype=None, cache=None, **kwargs) -> None: ...
    @property
    def path(self): ...
    @property
    def name(self): ...
    @property
    def mimetype(self): ...
    def exists(self, retrieve_if_missing: bool = True): ...
    def base64(self, encoding: str = 'ascii'): ...
    def invalidate(self) -> None: ...
    def download(self) -> None: ...
    def open(self, mode: str = 'rb'): ...
    def chunk(self, size: int = 5242880) -> Generator[Incomplete]: ...
    def __enter__(self): ...
    def __exit__(self, value_type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    @staticmethod
    def parse_url(url, verify_host: bool = True, mimetype_db=None, sanitize: bool = True): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __del__(self) -> None: ...
