from .. import exception as exception
from ..common import ContentLocation as ContentLocation
from .base import AttachBase as AttachBase
from _typeshed import Incomplete

class AttachMemory(AttachBase):
    service_name: Incomplete
    protocol: str
    location: Incomplete
    _data: Incomplete
    def __init__(self, content=None, name=None, mimetype=None, encoding: str = 'utf-8', **kwargs) -> None: ...
    def url(self, privacy: bool = False, *args, **kwargs): ...
    def open(self, *args, **kwargs): ...
    def __enter__(self): ...
    def download(self, **kwargs): ...
    def base64(self, encoding: str = 'ascii'): ...
    def invalidate(self) -> None: ...
    def exists(self): ...
    @staticmethod
    def parse_url(url): ...
    @property
    def path(self): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
